version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KC_HTTP_PORT: 8980
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8980:8980"
    depends_on:
      - postgres
    networks:
      - keycloak_net

  individuals-api:
    build:
      context: ./individuals-api
    container_name: individuals-api
    environment:
      - KEYCLOAK_BASEURL=http://keycloak:8980
      - KEYCLOAK_REALM=payment-system
      - KEYCLOAK_CLIENTID=individuals-api
      - KEYCLOAK_CLIENTSECRET=6Yh4GuJpOJeCMfAMYGFVjksElXKwpM3y
      - KEYCLOAK_CREDENTIALTYPE_PASSWORD=password
      - KEYCLOAK_CREDENTIALTYPE_CLIENTCREDENTIALS=client_credentials
      - KEYCLOAK_CREDENTIALTYPE_REFRESHTOKEN=refresh_token
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
    depends_on:
      - keycloak
    ports:
      - "8080:8080"
    networks:
      - keycloak_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - keycloak_net

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - keycloak_net
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  postgres_data:
  grafana-storage:

networks:
  keycloak_net:
