global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'individuals-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'individuals-api:8080' ]
