spring:
  application:
    name: individuals-api
server:
  port: 8080
keycloak:
  base-url: http://localhost:8980
  realm: payment-system
  client-id: individuals-api
  client-secret: "6Yh4GuJpOJeCMfAMYGFVjksElXKwpM3y"
  credential-type:
    password: password
    clientCredentials: client_credentials
    refreshToken: refresh_token