spring:
  application:
    name: individuals-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost:8980}/realms/payment-system
server:
  port: 8080
keycloak:
  base-url: http://${KEYCLOAK_HOST:localhost:8980}
  realm: payment-system
  client-id: individuals-api
  client-secret: "6Yh4GuJpOJeCMfAMYGFVjksElXKwpM3y"
  credential-type:
    password: password
    clientCredentials: client_credentials
    refreshToken: refresh_token
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      access: read_only
logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.security: DEBUG
